### ISSUE TITLE
Remove Poison dependency since it seems to be optional

### ISSUE THREAD

**Issue by sriedel** [matthewoden/libvault#15]
The way I'm reading the documentation, the json library can be any of the given libraries and Poison is purely optional. 
Since I"m already using Jason in my application, I would want to use that (and Vault.new/0 does return a vault structure with Jason as default json module.

However, I did encounter a dependency conflict as Poison recently a 4.0 version, which another dependency of my application already locked onto, but introducing libvault caused a dependency error, since it still requires ~> 3.0.

**Comment by matthewoden** [comment]
Yeah, I should probably remove both Jason and Poison (or rather, set them as `[:test, :dev]`) These were included as part of an earlier design.

**Comment by matthewoden** [comment]
Fixed in #17
