### ISSUE TITLE
Unsupported path error is raised

### ISSUE THREAD

**Issue by Nitrodist** [matthewoden/libvault#19]
Hello, I am implementing vault in an elixir project and tried `libvault` at first with no luck. Here is the error after authenticating successfully:

```
iex(op@10.10.10.10)3> {:ok, db_pass} = Vault.read(vault, "aws/sts/staging--www--stickfi--s3-cred")                  ** (MatchError) no match of right hand side value: {:error, ["1 error occurred:\n\n* unsupported path"]}
```

Here it is working with vaultex:

```
iex(optimus@10.10.10.10) 2> Vaultex.Client.read "aws/sts/staging--www--stickfi--s3-cred", :token, {"foo-bar-baz"}
{:ok,
 %{
   "access_key" => "foobarbaz",
   "secret_key" => "qux",
   "security_token" => "really-long-alphanumeric-string"
 }}

```

**Comment by matthewoden** [comment]
Sorry for the delay!

Can you give me a little more information about your vault configuration? I can see that you’re using the AWS sts path to get dynamic credentials, but is there any other configuration that you were passing in?

Is the example path accurate to what you were requesting? Or has it been cleaned up/redacted at all?

That error implies that there’s some measure of URI encoding that isn’t happening, but that path looks pretty straightforward.

**Comment by matthewoden** [comment]
Closing for now - feel free to reopen if you have more information.
